version: "3.9"

services:
  elector1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - data:/raft-cluster
      - /tmp/health/:/raft-cluster/health/
    environment:
      - SERVER_ADDR=elector1:50051
      - SERVER_ID=NodeA
      - STORAGE_DIR=/raft-cluster
      - BOOTSTRAP=false
      - TEST=true
      - HEALTH_CHECK_PATH=/raft-cluster/health/NodeA

  elector2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    volumes:
      - data:/raft-cluster
      - /tmp/health/:/raft-cluster/health/
    environment:
      - SERVER_ADDR=elector2:50052
      - SERVER_ID=NodeB
      - STORAGE_DIR=/raft-cluster
      - BOOTSTRAP=false
      - TEST=true
      - HEALTH_CHECK_PATH=/raft-cluster/health/NodeB

  elector3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    volumes:
      - data:/raft-cluster
      - /tmp/health/:/raft-cluster/health/
    environment:
      - SERVER_ADDR=elector3:50053
      - SERVER_ID=NodeC
      - STORAGE_DIR=/raft-cluster
      - BOOTSTRAP=false
      - TEST=true
      - HEALTH_CHECK_PATH=/raft-cluster/health/NodeC

volumes:
  data: