version: "3.9"

services:
  elector1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - data:/raft-cluster
    environment:
      - SERVER_ADDR=0.0.0.0:50051
      - SERVER_ID=NodeA
      - STORAGE_DIR=/raft-cluster
      - BOOTSTRAP=false

  elector2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    volumes:
      - data:/raft-cluster
    environment:
      - SERVER_ADDR=0.0.0.0:50052
      - SERVER_ID=NodeB
      - STORAGE_DIR=/raft-cluster
      - BOOTSTRAP=false

  elector3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    volumes:
      - data:/raft-cluster
    environment:
      - SERVER_ADDR=0.0.0.0:50053
      - SERVER_ID=NodeC
      - STORAGE_DIR=/raft-cluster
      - BOOTSTRAP=false

volumes:
  data:
